name: Automatic Github release

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - VERSION

jobs:
  github:
    permissions:
      contents: write
    uses: michaelpaul/release-automation-action/.github/workflows/reusable-github-release.yml@v1.0.10
    with:
      release-title: Adyen Node API Library 
      develop-branch: develop
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
