name: Release request

on:
    workflow_dispatch:
      inputs:
        prerelease:
          required: false
          type: boolean
          default: false
          description: "This release will be labeled as non-production ready"
    push:
      branches:
        - develop
        - custom-action

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    name: A job using a custom action
    steps:
      - uses: michaelpaul/release-automation-action@composite
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pre-release: ${{ inputs.prerelease || false }}
