name: Prepare release

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
      - labeled
      - unlabeled
    branches:
      - develop

jobs:
  candidate:
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged && !startsWith(github.head_ref, 'promote/'))
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare the next main release
        uses: Adyen/release-automation-action@v1.0.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          develop-branch: develop
          version-files: package.json