name: Release request

on:
    workflow_dispatch:
      inputs:
        prerelease:
          required: false
          type: boolean
          default: false
          description: "This release will be labeled as non-production ready"
    push:
      branches:
        - develop
        - custom-action

jobs:
  main:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Prepare the next main release
        uses: michaelpaul/release-automation-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pre-release: ${{ inputs.prerelease || false }}
