name: Sync two branches

on: [ workflow_dispatch ]

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: develop