name: Sync two branches

on: [ workflow_dispatch ]

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
      - name: Reset promotion branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Prepare release request
        uses: actions/github-script@v6
        id: release
        with:
          debug: true
          script: |
            const release = require('./.github/scripts/release.js')
            await release.releaseRequest(github, core);
      - name: Bump package.json
        run: npm --no-git-tag-version version ${{steps.release.outputs.increment}}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: automation/release
          title: Release v${{steps.release.outputs.nextVersion}}
